# @package _global_
pickle_normal: /neurospin/dico/jchavas/Runs/35_cingulate_with_distance/Input/Processed_External/crops/2mm/CINGULATE/mask/Rskeleton.pkl
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/jchavas/Runs/35_cingulate_with_distance/Input/HCP_half_1bis.csv
nb_subjects: -1
