# @package _global_
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabel.npy
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/ACCpatterns/train_val_ACCpatterns.csv
nb_subjects: -1
subject_labels_file: /neurospin/dico/data/bv_databases/human/partially_labeled/ACCpatterns/all.csv
#label_names: ["NEOFAC_A", "NEOFAC_O", "NEOFAC_C", "NEOFAC_N", "NEOFAC_E"]
#label_names: ["NEOFAC_C"]
label_names: ["Gender"]