# @package _global_
dataset_name: cingulate_schizconnect
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
#foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rlabel.npy
#subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rlabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rcrops
crop_file_suffix: _ses-v1_cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/crops/2mm/CINGULATE/mask/Rlabels
pickle_benchmark: 
#train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/schizconnect-vip-prague/train_val_ACCpatterns.csv
nb_subjects: -1
subject_labels_file: /neurospin/dico/data/bv_databases/human/partially_labeled/schizconnect-vip-prague/all.csv
subject_column_name: 'participant_id'
label_names: ["diagnosis"]