# @package dataset.STs_HCP_stratified_extreme_Flanker_right
dataset_name: STs_HCP_stratified_extreme_Flanker_right
pickle_normal: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rskeleton.pkl
numpy_all: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rskeleton.npy
subjects_all: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rskeleton_subject.csv
crop_dir: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rcrops
foldlabel_dir: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rlabels
foldlabel_all: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rlabel.npy
subjects_foldlabel_all: /home_local/jc225751/Runs/61_classifier_regresser/Input/crops/S.T.s./mask/Rlabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_train_subjects.csv
val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_val_subjects.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/extreme_flanker_test_subjects.csv
# subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/participants_age_continuous.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp-top-separated/participants.csv
subject_column_name: 'Subject'
label_scaling:
input_size: (1, 24, 52, 51)
