# @package _global_
model: SimCLR_supervised
with_labels: True
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.3
sigma_labels: 2.0
sigma: 5
drop_rate: 0.05
proportion_pure_contrastive: 1.0  # only used in the encoder case
#pretrained_model_path:
pretrained_model_path: /neurospin/dico/jlaval/Runs/01_deep_supervised/Program/Output/2023-06-15/14-36-49/logs/lightning_logs/version_0/checkpoints/epoch=250-step=297435.ckpt # STS UKB
#/path/to/FILE.ckpt
load_encoder_only: True
