# @package _global_
model: SimCLR_supervised
input_size: (1, 20, 48, 48)
patch_size: [1, 10, 24, 24]
depth_decoder: 3
temperature_initial: 0.1
temperature: 0.1
sigma_labels: 0.1
sigma: 5
proportion_pure_contrastive: 1.0
drop_rate: 0.