# @package _global_
model: SimCLR_fusion
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.3
sigma_labels: 2.0
sigma: 5
drop_rate: 0.05
pretrained_model_path: # /volatile2/jc225751/Runs/61_classifier_regresser/Program/Output/2023-09-13_SimCLR_pretrained_UKB/11-22-56_110/logs/lightning_logs/version_0/checkpoints/epoch=250-step=297435.ckpt #/path/to/FILE.ckpt
load_encoder_only: True
fusioned_latent_space_size: 10
converter_activation: relu
