# @package _global_
model: SimCLR_fusion
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.3
sigma_labels: 2.0
sigma: 5
drop_rate: 0.05
pretrained_model_path: /neurospin/dico/agaudin/Runs/09_new_repo/Output/supervised/pretrained_UKB/UKB_pretrained_weights.ckpt
load_encoder_only: True
freeze_encoders: True
fusioned_latent_space_size: -1
converter_activation: relu