# @package _global_
model: SimCLR_supervised
with_labels: True
input_size: (1, 20, 42, 38)
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.3
sigma_labels: 2.0
sigma: 5
drop_rate: 0.05
proportion_pure_contrastive: 0.0
depth_decoder: 3