# @package _global_
model: SimCLR_supervised
with_labels: True
input_size: (1, 20, 48, 48)
temperature_initial: 0.1
temperature: 0.1
sigma_labels: 0.1
sigma: 5
proportion_pure_contrastive: 0.9
drop_rate: 0.
depth_decoder: 3