# @package _global_
# define path and parameters needed for the classifier on the latent space
training_embeddings: /neurospin/dico/agaudin/Runs/03_monkeys/Output/2022-07-05/foldlabel_30/ACCpatterns_embeddings/full_embeddings.csv
embeddings_of_interest:
results_save_path:
training_labels: /neurospin/dico/data/bv_databases/human/partially_labeled/ACCpatterns/all.csv
labels_of_interest:
classifier_hidden_layers: [10]
classifier_activation: None
classifier_loss: MSE
class_max_epochs: 10
class_batch_size: 10
n_repeat: 250
classifier_seed: 24
classifier_test_size: 0.2