# @package _global_
batch_size: 16
pin_mem: True
lr: 5e-3
weight_decay: 5.0e-05
max_epochs: 100
nb_epochs_per_saving: 1
nb_epochs_per_tSNE: 25
nb_epochs_per_matrix_plot: -1
nb_steps_per_flush_logs: 1
log_every_n_steps: 2
early_stopping_patience: 25
start_epoch: 0
checkpoint_path:
analysis_path: 
verbose: 1
checking: False
# Data split and subject choice
seed: 1
partition: [0.9, 0.1]
nb_subjects: -1
random: True
random_state:
# pretrained_model_path: /neurospin/dico/data/deep_folding/papers/ipmi2023/models/contrastive/trained_on_HCP_half_1/gridsearch/joel/convnet-10/23-11-12_2/logs/default/version_0/checkpoints/epoch=250-step=7780.ckpt
pretrained_model_path: 
