# @package _global_
resize: False
both: False
apply_augmentations: True
mixed: True
foldlabel: True
trimdepth: True
fill_value: 0
max_angle: 6
max_distance: 8
checkerboard_size: 4
keep_bottom: True
percentage: 40
variable_percentage: False
sigma_noise: 0.2  # set to positive to allow noise
patch_size: [1, 11, 25, 25]