# @package _global_
resize: False
both: False
apply_augmentations: True
mixed: False
foldlabel: False
trimdepth: True
fill_value: 0
max_angle: 6
max_distance: 6
max_translation: 1
checkerboard_size: 4
keep_bottom: True
sigma_noise: 0.2  # set to positive to allow noise
