# @package dataset.cingulate_HCP
dataset_name: cingulate_HCP
pickle_normal: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rskeleton.pkl
numpy_all: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rskeleton_subject.csv
crop_dir: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rcrops
foldlabel_dir: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rlabels
foldlabel_all: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rlabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: /volatile/jl274628/data/hcp/2mm/CINGULATE/mask/2mm/CINGULATE/mask/Rskeleton_subject_full.csv
subject_labels_file: /volatile/jl274628/data/hcp/participants.csv
subject_column_name: 'Subject'
input_size: (1, 17, 40, 38)