defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_HCP
  - model: SimCLR
  - mode: encoder
  - augmentations: no_foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings