# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_ACCpatterns
  - model: SimCLR_supervised
  - mode: evaluation
  - augmentations: no_foldlabel
  - backbone: DenseNet
  - platform: cuda_not_brainvisa
  - trainer: default
