defaults:
  - _self_
  - augmentations: foldlabel
  - backbone: ConvNet
  - classifier: svm
  - dataset/postcentral_schiz_R_strat_bis
  - dataset/postcentral_schiz_L_strat_bis
  - embeddings: embeddings
  - hydra: local
  - label: diagnosis
  - mode: classifier
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb/identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}