# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_HCP
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: no_foldlabel
  - backbone: DenseNet
  - platform: cuda_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings