defaults:
  - _self_
  - augmentations: foldlabel
  - backbone: ConvNet
  - classifier: svm
  - dataset/cingulate_HCP_stratified_left
  - dataset/cingulate_HCP_stratified_right
  - embeddings: embeddings
  - hydra: local
  - label: Flanker_AgeAdj_class
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: linear
  - trainer: default
  - wandb: sweep
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}