defaults:
  - _self_
  - augmentations: foldlabel
  - backbone: ConvNet
  - classifier: svm
  - dataset/BROCA_HCP_stratified_extreme_Flanker_left
  - dataset/BROCA_HCP_stratified_extreme_Flanker_right
  - embeddings: embeddings
  - hydra: local
  - label: Flanker_AgeAdj_class
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: linear
  - trainer: SimCLR
  - wandb: not_used
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
