defaults:
  - _self_
  - augmentations: foldlabel
  - backbone: ConvNet
  - classifier: svm
  - dataset/STs_babies/STs_UkBioBank
  # - dataset/occipital_schiz_L_strat_bis_threshold1
  - embeddings: embeddings
  - hydra: local
  - label: diagnosis
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb: identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
