# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_ACCpatterns
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: DenseNet
  - platform: cpu
  - trainer: default
  - classifier: binary_classifier
  - embeddings: embeddings