defaults:
  - _self_
  - hydra: local
  - dataset/S.T.s_dHCP_374_subjects
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: linear
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
