defaults:
  - hydra: local
  - dataset:
    - cingulate_HCP_half_1
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - override hydra/job_logging: custom