defaults:
  - _self_
  - hydra: local
  - dataset/cingulate_HCP_half_1
  - label: Right_PCS
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: linear
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}