# @package _group_
defaults:
  - hydra: no_save
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled
  - dataset: cingulate_ACCpatterns
  - model: SimCLR
  - mode: encoder
  - augmentations: no_foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: binary_classifier
  - embeddings: embeddings