# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_ACCpatterns
  - model: SimCLR
  - augmentations: default
  - backbone: DenseNet
  - platform: cuda_brainvisa

