# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_intersect_chimps
  - model: SimCLR
  - mode: encoder
  - augmentations: no_foldlabel
  - backbone: DenseNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: binary_classifier
  - embeddings: embeddings