defaults:
  - _self_
  - augmentations: random
  - backbone: ConvNet
  - classifier: svm
  - dataset/local_julien/cingulate_UKB_right
  # - dataset/occipital_schiz_L_strat_bis_threshold1
  - embeddings: embeddings
  - hydra: local
  - label: Preterm_28
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb: identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
