defaults:
  - _self_
  - hydra: local
  - dataset/cingulate_ACCpatterns
  - dataset/left_cingulate_ACCpatterns
  - label: PCS_asymetry
  - model: SimCLR_fusion
  - mode: classifier
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: linear
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}