# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_ACCpatterns
  - model: SimCLR
  - mode: encoder
  - augmentations: no_foldlabel
  - backbone: DenseNet
  - platform: cuda_brainvisa
  - trainer: default
