defaults:
  - _self_
  - hydra: local
  - dataset/cingulate_schiz
  - dataset/cingulate_schiz_left
  - label: diagnosis
  - model: SimCLR_fusion
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: linear
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}