defaults:
  - _self_
  - hydra: local
  - dataset/right_cingulate_HCP_full_nb_voxels
  - dataset/left_cingulate_HCP_full_nb_voxels
  - model: SimCLR_supervised
  - mode: regresser
  - augmentations: foldlabel
  - backbone: DenseNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: relu
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}