defaults:
  - hydra: local
  - dataset: cingulate_HCP_full
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - override hydra/job_logging: custom