# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: DenseNet
  - platform: cuda_not_brainvisa
  - trainer: default
