defaults:
  - hydra: local
  - dataset: cingulate_HCP_half_1
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: DenseNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - projection_head: linear
  - override hydra/job_logging: custom