defaults:
  - hydra: local
  - dataset: S.T.s_dHCP_374_subjects.yaml 
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - override hydra/job_logging: custom
