defaults:
  - hydra: no_save
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled
  - dataset: test_cingulate_ACCpatterns
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings