defaults:
  - _self_
  - augmentations: random
  - backbone: ConvNet
  - classifier: svm
  # - dataset/local_julien/cingulate_UKB_right.yaml
  #- dataset/local_julien/1-5mm/STs_babies_UKB_right_1-5mm
  - dataset/local_julien/1-5mm/orbital_UKB_left_1-5mm
  #- dataset/local_julien/1-5mm/cingulate_UKB_right_1-5mm.yaml
  #- dataset/local_julien/old/STs_UkBioBank.yaml
  # - dataset/occipital_schiz_L_strat_bis_threshold1
  - embeddings: embeddings
  - hydra: local
  - label: Preterm_28
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb: identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
