defaults:
  - _self_
  - augmentations: translation_only
  - backbone: ConvNet
  - classifier: svm
  - dataset_localization: kraken_Run70
  - dataset/with_reskel_distbottom/2mm/schiz/SC_SPeC_left
  - dataset/with_reskel_distbottom/2mm/schiz/SC_SPeC_right
  # - dataset/local_julien/cingulate_UKB_right.yaml
  #- dataset/local_julien/1-5mm/STs_babies_UKB_right_1-5mm
  # - dataset/local_julien/1-5mm/orbital_UKB_left_1-5mm
  #- dataset/local_julien/1-5mm/cingulate_UKB_right_1-5mm.yaml
  #- dataset/local_julien/old/STs_UkBioBank.yaml
  # - dataset/occipital_schiz_L_strat_bis_threshold1
  - embeddings: embeddings
  - hydra: local
  - label: diagnosis
  - mode: classifier
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb: identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
datakey: ${oc.dict.keys:dataset}
