program: train.py
entity: aymeric-gaudin
project: 2023_brain_regions_grid_searches
method: random
metric:
  goal: minimize
  name: gs_criterion
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  drop_rate:
    min: 0.
    max: 0.20
  sigma_noise:
    min: 0.
    max: 0.5
  max_angle:
    min: 0
    max: 6

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}