program: train.py
project: flanker-test
method: bayes
metric:
  goal: minimize
  name: gs_criterion_best
parameters:
  lr:
    # distribution: log_uniform_values
    min: 0.0001
    max: 0.0002
  drop_rate:
    min: 0.25
    max: 0.35
  gamma:
    min: 0.9
    max: 1.0
  # sigma_noise:
  #   min: 0.
  #   max: 0.5
  # max_angle:
  #   min: 0
  #   max: 6

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}