program: train.py
entity: aymeric-gaudin
project: 2023_brain_regions_grid_searches
method: random
metric:
  goal: minimize
  name: gs_criterion
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  drop_rate:
    min: 0.
    max: 0.20
  sigma_noise:
    min: 0.
    max: 0.5
  max_angle:
    min: 0
    max: 6
  
  +dataset:
    value: [frontal_schiz_R_strat_bis, frontal_schiz_L_strat_bis]
  
  output_dir:
    value: /neurospin/dico/agaudin/Runs/09_new_repo/Output
  suffix_dir:
    value: _frontal

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
