program: train.py
entity: joel-chavas
project: inhibitory
method: random
metric:
  goal: minimize
  name: gs_criterion
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  drop_rate:
    min: 0.05
    max: 0.3
  gamma:
    min: 0.7
    max: 1.0
  +dataset:
    value: [SFintermediate_HCP_stratified_extreme_Flanker_left, SFintermediate_HCP_stratified_extreme_Flanker_right]
  output_dir:
    value: /home_local/jc225751/Runs/61_classifier_regresser/Program/Output
  suffix_dir:
    value: _SFintermediate
  # sigma_noise:
  #   min: 0.
  #   max: 0.5
  # max_angle:
  #   min: 0
  #   max: 6

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
