# @package _global_
hydra:
  job:
    chdir: True
  run:
    dir: ../../Output/${now:%Y-%m-%d}/${now:%H-%M-%S}_${get_train_seed:}
  sweep:
    dir: ../../Output/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${hydra.job.num}
checkpoint_dir: ../../Output
