# @package _global_
hydra:
  run:
    dir: ../../Output/supervised/ACCpatterns/L/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ../../Output/supervised/ACCpatterns/L/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${hydra.job.num}
checkpoint_dir: ../../Output
