# @package _global_
# Characterization of the DenseNet model used
backbone_name: convnet
encoder_depth: 3
num_representation_features: 30
num_outputs: 30
projection_head_hidden_layers:
drop_rate: 0.15