# @package _global_
# define path and parameters needed for the classifier on the latent space
model_path: "/volatile/jc225751/Runs/43_supervised_contrastive_ACCpatterns/Output/2022-06-13/10-00-13"
embeddings_save_path: "/volatile/jc225751/Runs/43_supervised_contrastive_ACCpatterns/Output/2022-06-13/10-00-13/ACCpatterns_embeddings/${now:%Y-%m-%d_%H-%M}/"