# @package _global_
# define path and parameters needed for the classifier on the latent space
model_path: "/neurospin/dico/agaudin/Runs/02_explicabilite_humains_2022/Output/2022-06-02/16-55-07"
embeddings_save_path: "/neurospin/dico/agaudin/Runs/02_explicabilite_humains_2022/Output/2022-06-02/16-55-07/ACCpatterns_embeddings/${now:%Y-%m-%d_%H-%M}/"